config/routes.rb
Superforum::Application.routes.draw do
  
  get "search/index"
  root :to => "resources#index"
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :topics do
    resources :subjects do
      resources :comments
    end
  end

  resources :resources
  resources :places
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    resources :items
    resources :messages
  end
  resources :password_resets
  get 'tags/:tag', to: 'users#index', as: :tag
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :subject
	belongs_to :user
	mount_uploader :photo, PhotoUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :description, :name, :address, :phone, :email, :category, :presence => true
	geocoded_by :address
	after_validation :geocode 
	scope :closest_three, -> {limit(3)}
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments
	accepts_nested_attributes_for :comments

	mount_uploader :photo, PhotoUploader
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates :description, :name, :presence => true
	belongs_to :forum
	belongs_to :user
	# has_many :posts, :dependent => :destroy
	has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :subjects
  has_many :comments
  has_many :topics
  has_many :items
  has_many :messages
  has_many :messages_received, class_name: "Message", foreign_key: :recipient_id


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  	@topics = Topic.all
  end

  def show
  	@topic = Topic.find(params[:id])
  end

  def new
  	@topic = Topic.new
  end

  def edit
  	@topic = Topic.find(params[:id])
  end

  def create
  	@topic = Topic.new(topic_params)

    @topic.user_id = current_user.id
  	if @topic.save
  		redirect_to topics_url
  	else
  		render :new
  	end
  end

  def update
  	@topic = Topic.find(params[:id])

  	if @topic.update_attributes(topic_params)
  		redirect_to topic_path(@topic)
  	else
  		render :edit
  	end
  end

  def destroy
  	@topic = Topic.find(params[:id])
  	@topic.destroy
  	redirect_to topics_path
  end

  private
  def topic_params
  	params.require(:topic).permit(:name, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_date(deadline)
		"#{deadline.in_time_zone('Eastern Time (US & Canada)').strftime('%b/%d/%Y - %H:%M')}"
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
	def hours(something)
		something.strftime("%H:%M")
	end

  def find_bookstores(places)
    @bookstores = []
    places.each do |p|
      if p.category == "Books"
        @bookstores << p
      end
    end
    return @bookstores
  end
end


#need to change to mon opening hours... mon closing hours etc

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/_form.html.erb
<div class="form">
  <div class="row">
      <div class="large-12 columns">
		<%= form_for(@topic) do |f| %>
		<% if @topic.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

				<ul>
					<% @topic.errors.full_messages.each do |msg| %>
						<li>
								<%= msg %>
							<% end %>
						</li>
				</ul>
			</div>
		<% end %>
			<%= f.hidden_field :user_id %>

			<div class="field">
				<%= f.label :name %><br/>
				<%= f.text_field :name %><br/>
			</div>
			<div class="field">
				<%= f.label :description %><br/>
				<%= f.text_field :description %><br/>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
		<% end %>
	   </div>
	</div>
</div>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Superforum</h1>
<% if current_user %>
  <%= link_to "Add New Topic", new_topic_path %></p>
<% else %>
	<p>You must <%= link_to "Register", signup_path %> or <%= link_to "Log In", :login %> </p> to add a new topic.</p>

<% end %>
<p>Welcome to Superforum. Here you can interact with other users by creating and discussing your own topics. 
Please read the rules before posting or replying to threads. Otherwise you may get banned! Have fun.</p>
<p>Click on a topic name to see all of its threads.</p>

<div class="form">

  <div class="row">
    <div class="large-12 columns">
   
        <%= form_tag("/search/index", method: "get") do %>
          <%= label_tag(:search, "Search Superforum") %>
          <%= text_field_tag(:search) %>
          <%= submit_tag("Search") %>
      
    </div>
  </div>

</div>
<% end %>

<table border="1" align="center">  
  <tr>  
    <th width="30%">Topic</th>  
    <th width="30%">Description</th>  
    <th width="30%">Last Post</th>
  </tr>  
  <% @topics.each do |t| %>

  <tr>
    <td>
      <%= link_to t.name, topic_path(t) %>
    </td>
    <td>
      <%= t.description %>
    </td>
    <td>
      <%= display_date(t.updated_at) %>
    </td>
  </tr>
      <% end %>
</table>  

app/views/topics/new.html.erb
<h1>Create a New Topic</h1>

<%= render 'form' %>

<%= link_to 'Dashboard', topics_path %>

app/views/topics/show.html.erb
<h1>All Threads For <%= @topic.name %></h1>



<ul class="breadcrumbs">
  <li><a href="#"><%= link_to "Superforum", topics_path %></a></li>
  <li class="current"><a href="#"><%= @topic.name %></a></li>
</ul>


<!-- 
<p><%= @topic.description %></p> -->
<% if current_user == @topic.user || current_user.try(:admin?) %>
  <%= link_to "Delete this Topic", topic_path(@topic), :confirm => "Are you sure you want to delete this topic?", :method => :delete %>
<% end %>
<% if current_user %>
  <p><%= link_to "Post a New Thread", new_topic_subject_path(@topic) %></p>
<% else %>
  <p>You must <%= link_to "Register", signup_path %> or <%= link_to "Log In", :login %> to create a new thread.</p>
<% end %>


<table border="1" align="center">  
  <tr>  
    <th width="30%">Thread</th>  
    <th width="30%">Description</th>
    <th width="30%">Last Post Made</th>  
  </tr>  
  <% @topic.subjects.each do |x| %>
  <tr>
  	<td>
     <%= link_to x.name, topic_subject_path(@topic, x) %>
      <% if current_user == @topic.user || current_user.try(:admin?) %>
      <%= link_to "(Delete this Thread)", topic_subject_path(@topic, x), :confirm => "Are you sure you want to delete this thread?", :method => :delete %> 
      <% end %>
	</td>
	<td>
		<%= x.description %>
	</td>
  <td>
    <%= display_date(x.created_at) %>
  </td>
  </tr>

  
  	<% end %>
</table>  