config/routes.rb
Superforum::Application.routes.draw do
  
  get "search/index"
  root :to => "resources#index"
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :topics do
    resources :subjects do
      resources :comments
    end
  end

  resources :resources
  resources :places
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    resources :items
    resources :messages
  end
  resources :password_resets
  get 'tags/:tag', to: 'users#index', as: :tag
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :subject
	belongs_to :user
	mount_uploader :photo, PhotoUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :description, :name, :address, :phone, :email, :category, :presence => true
	geocoded_by :address
	after_validation :geocode 
	scope :closest_three, -> {limit(3)}
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments
	accepts_nested_attributes_for :comments

	mount_uploader :photo, PhotoUploader
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates :description, :name, :presence => true
	belongs_to :forum
	belongs_to :user
	# has_many :posts, :dependent => :destroy
	has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :subjects
  has_many :comments
  has_many :topics
  has_many :items
  has_many :messages
  has_many :messages_received, class_name: "Message", foreign_key: :recipient_id


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		if params[:tag]
      @items = Item.tagged_with(params[:tag])
    else
    	@items = Item.all
    end
	end

	def new
		@user = User.new
	end

	# def destroy
	# 	@message = Message.find(params[:id])
	# 	@message.destroy
	# 		redirect_to user_path(@user)
	# end

	def create
		@user = User.new(user_params)
		if @user.save
			auto_login(@user)
			"Welcome to Superforum!"
			redirect_to topics_url, :notice => "Signed up!"
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		@recipient = User.find(params[:id])
		if current_user
			@message = Message.new
			@message.recipient_id = @recipient.id
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to user_path(@user)
		else
			render :edit
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	private
  	def user_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation, :profile, :admin)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_date(deadline)
		"#{deadline.in_time_zone('Eastern Time (US & Canada)').strftime('%b/%d/%Y - %H:%M')}"
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
	def hours(something)
		something.strftime("%H:%M")
	end

  def find_bookstores(places)
    @bookstores = []
    places.each do |p|
      if p.category == "Books"
        @bookstores << p
      end
    end
    return @bookstores
  end
end


#need to change to mon opening hours... mon closing hours etc

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_messages.html.erb
<h3><%= @user.username %>'s Messages</h3>
<% if current_user == @user %>
	<div id="message-list">
		<% @user.messages.each do |message| %>
				<div class="message">
					<p style="color:white"><%= message %></p>
					<br>
					<div class="sender">
						<% if message.user != nil %>
						<em> by <%= message.username %></em>
						Added on: <%= message.created_at %>
						<% end %>
						<%= link_to "Delete this message", user_message_path(@user, message), :confirm => "Are you sure you want to delete this message?", :method => :delete %>
					</div>
				</div>
		<% end %>
	</div>	
<% end %>

app/views/users/edit.html.erb
<p>My Profile</p>

<p>Hello, <%= @user.username %>.</p>
<p>Tell us about yourself.</p>

<!-- 
<%= @user.profile %> -->
<div class="form">
  <div class="row">
      <div class="large-12 columns">
		<%= form_for(@user) do |f| %>
		<%= f.text_area :profile %>
	  </div>
  </div>
</div>

	<%= f.submit %>
<% end %>

<p><%= link_to "Back to Home", topics_url %></p>

app/views/users/index.html.erb
<h1>Clothing Swap</h1>
<% if current_user %>
	<h4><%= link_to "post new clothing", new_user_item_path(current_user.id) %></h4>

<% else %>
	<h4><%= link_to "post new clothing", login_path %></h4>
<% end %></br>


<h4>search by tag:</h4>
<div id="tag_cloud">
  <% tag_cloud Item.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div></br></br>
				
<div class="form">

  <div class="row">
      <div class="large-12 columns">
        
					<%= form_tag("/search/index", method: "get") do %>
					  <%= label_tag(:search, "Search All Items and Wishlists") %>
					  <%= text_field_tag(:search) %>
					  <%= submit_tag("Search") %>
					<% end %>
			
			</div>
	</div>

</div>
<div class="row">
	<h4>all items:</h4>
<%# @users.each do |x| %>

		<ul class="medium-4 column">
		<%# x.items.each do |i| %>
		<% @items.each do |i| %>
					<div class="swap-item">
						<%= i.name %></br>
						Posted by: <%= link_to i.user.username, user_path(i.user_id) %></br>
						<%= image_tag i.image_url :thumb %></br>
						<%= link_to "See More", user_items_path(i.user_id)%>
					</div>
		<% end %>
		</ul>
</div>

<%# end %>

app/views/users/new.html.erb
<h1>Registration</h1>

<div class="form">
  <div class="row">
      <div class="large-12 columns">
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
					<div class="error_messages">
					<h5>Form is invalid</h5>
					<ul>
						<% for message in @user.errors.full_messages %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<div class="field">
				<%= f.label :username %>
				<%= f.text_field :username %>
			</div>

			<div class="field">
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div class="field">
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>
			<div class="field">
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</div>
			<div class="actions"><%= f.submit %></div>
		<% end %>			
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
	<h1> Welcome <%= @user.username %> </h1>
	<p><%= link_to "Edit My Profile", edit_user_path %> |
		<%= link_to "See My Swaps", user_items_path(@user) %> |
	   <%= link_to "Back To Home", resources_url %></p>
	<p>Your profile:</p>
	<p>
		<b>
		<%= @user.profile %>
		</b>
	</p>
	<% @user.messages_received.each do |x| %>
			<p>To: <%= x.recipient.username %>, From: <%= x.user.username %></p>
			<p><%= x.title %></p>
			<p><%= x.content %></p>
			
	<% end %>
<% else %>
	<h1> <%= @user.username %> 's Profile</h1>
	<p><%= link_to "See My Swaps", user_items_path(@user) %> |
	<%= link_to "Back To Home", resources_url %></p>

	<p>
		<b>
			<%= @user.profile %>
		</b>
	</p>
<% end %>
<% if current_user != @user %>

<p>Send a Message to <%= @user.username %>:</p>

<div class="form">
  <div class="row">
      <div class="large-12 columns">
				<%= form_for [@user, @message] do |f| %>
				<% if @message.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

						<ul>
							<% @message.errors.full_messages.each do |msg| %>
								<li>
										<%= msg %>
									<% end %>
								</li>
						</ul>
					</div>
				<% end %>

				<%= f.hidden_field :recipient_id %>

				<div class="field">
					<%= f.label "Subject" %><br/>
					<%= f.text_field :title %><br/>
				</div>
				<div class="field">
					<%= f.label "Message" %><br/>
					<%= f.text_area :content %><br/>
				</div>
				<p>From <%= current_user.username %></p>
				<div class="actions">
					<%= f.submit %>
				</div>
			<% end %>
		</div>
	</div>
</div>
<% elsif current_user == @user %>
	<p></p>
<% else %>
	<p><%= link_to "Log In", login_path %> to trade with <%= @user.username %>.</p>
<% end %>