config/routes.rb
Superforum::Application.routes.draw do
  
  get "search/index"
  root :to => "resources#index"
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :topics do
    resources :subjects do
      resources :comments
    end
  end

  resources :resources
  resources :places
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    resources :items
    resources :messages
  end
  resources :password_resets
  get 'tags/:tag', to: 'users#index', as: :tag
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :subject
	belongs_to :user
	mount_uploader :photo, PhotoUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :description, :name, :address, :phone, :email, :category, :presence => true
	geocoded_by :address
	after_validation :geocode 
	scope :closest_three, -> {limit(3)}
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments
	accepts_nested_attributes_for :comments

	mount_uploader :photo, PhotoUploader
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates :description, :name, :presence => true
	belongs_to :forum
	belongs_to :user
	# has_many :posts, :dependent => :destroy
	has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :subjects
  has_many :comments
  has_many :topics
  has_many :items
  has_many :messages
  has_many :messages_received, class_name: "Message", foreign_key: :recipient_id


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_filter :ensure_logged_in, :only => [:edit, :create, :update, :destroy]
  before_filter :load_user

	def index
    if params[:tag]
      @items = Item.tagged_with(params[:tag])
    else
    	@items = Item.all
    end
  end

  def show
  	@item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def create
    @item = @user.items.build(item_params)

    @item.user_id = current_user.id
    # respond_to do |format|
      if @item.save
        render :index
      else
        render :new
      end
  end

  def tag_cloud
    @tags = Item.tag_counts_on(:tags)
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update_attributes(item_params)
  		redirect_to user_items_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@item = Item.find(params[:id])
  	@item.destroy
  	redirect_to user_items_path
  end

  private
  def item_params
  	params.require(:item).permit(:name, :description, :user_id, :image, :tag_list)
  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_date(deadline)
		"#{deadline.in_time_zone('Eastern Time (US & Canada)').strftime('%b/%d/%Y - %H:%M')}"
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
	def hours(something)
		something.strftime("%H:%M")
	end

  def find_bookstores(places)
    @bookstores = []
    places.each do |p|
      if p.category == "Books"
        @bookstores << p
      end
    end
    return @bookstores
  end
end


#need to change to mon opening hours... mon closing hours etc

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<h1>Post New Clothing</h1>


<div class="form">
  <div class="row">
      <div class="large-12 columns">
			<%= form_for [@user, @item],  :html => { :multipart => true} do |i| %>
			  		<% if @item.errors.any? %>
			    	<div id="error_explanation">
				     	<h2>
				     		<%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:
				     	</h2>

			     		<ul>
				      		<% @item.errors.full_messages.each do |msg| %>
				       		<li><%= msg %></li>
			     			<% end %>
			      		</ul>
			   		</div>
			  		<% end %>
					<div class="field">
						<%= i.label :name %><br/>
						<%= i.text_field :name %>
					</div>
					<p>Write a description of your clothing and include a wishlist for what you would like to trade for.</p>
					<div class="field">
						<%= i.label :description %><br/>
						<%= i.text_area :description %>
					</div>
			    <div class="field">
			      <%= i.label :tag_list, "Tags (separated by commas)" %></br>
			      <%= i.text_field :tag_list %>
					<div class="field">
						<%= i.label :image %><br/>
						<%= i.file_field :image %>
					</div>
					
					
					
					<div class="actions">
						<%= i.submit %>
					</div>
			<% end %>
		</div>
	</div>
</div>

app/views/items/edit.html.erb
<h2>Edit this Item</h2>

<%= render 'form' %>

app/views/items/index.html.erb
<% if current_user == @user %>
<h1>My Clothing Swap</h1>
<% else %>
<h1><%= @user.username %> 's Clothing to Swap</h1>
<ul>Contact: <%= link_to @user.username, user_path(@user) %></ul>
<% end %>

<% if current_user == @user %>
  <p><%= link_to "Post New Clothing", new_user_item_path(current_user.id) %></p>
<% else %>
  <%= link_to "Post New Clothing", login_path %>
<% end %></br>

<h4>search by tag:</h4>
<div id="tag_cloud">
  <% tag_cloud Item.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div></br>

<!-- form for new item listing -->
<!--display all items w users, tags, categories, pictures -->


<% @user.items.each do |i| %>
<ul class="small-block-grid-3">
	<li><b><%= i.name %>:</b> <%= i.description %>
		<!-- <p>Created at: <%= i.display_date %></p> -->
	</li>
	<li><%= link_to image_tag( i.image.url ), user_item_path(@user, i) %></li>
</ul>
<% end %>

app/views/items/new.html.erb
<h1>My Clothing Swap</h1>

<%= render 'form' %>
<%= link_to "Back", resources_path %>

app/views/items/show.html.erb
<p>
<b><%= @item.name %></b>: 
<%= @item.description %>
<p>

<% if current_user == @user %>
  <%= link_to "Delete this Item", {:user_id => @user.id, :id => @item.id}, :confirm => "Are you sure you want to delete this item?", :method => :delete %>| <%= link_to "Edit Item", edit_user_item_path(@user, @item) %>
<% end %>

<p><%= image_tag( @item.image.url ) %></p>
<p>Tags: <%= raw @item.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></p>