config/routes.rb
Superforum::Application.routes.draw do
  
  get "search/index"
  root :to => "resources#index"
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :topics do
    resources :subjects do
      resources :comments
    end
  end

  resources :resources
  resources :places
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    resources :items
    resources :messages
  end
  resources :password_resets
  get 'tags/:tag', to: 'users#index', as: :tag
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :subject
	belongs_to :user
	mount_uploader :photo, PhotoUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
  acts_as_taggable
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipient, :foreign_key => "recipient_id", :class_name => "User"
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :description, :name, :address, :phone, :email, :category, :presence => true
	geocoded_by :address
	after_validation :geocode 
	scope :closest_three, -> {limit(3)}
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments
	accepts_nested_attributes_for :comments

	mount_uploader :photo, PhotoUploader
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates :description, :name, :presence => true
	belongs_to :forum
	belongs_to :user
	# has_many :posts, :dependent => :destroy
	has_many :subjects
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :subjects
  has_many :comments
  has_many :topics
  has_many :items
  has_many :messages
  has_many :messages_received, class_name: "Message", foreign_key: :recipient_id


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
	def hours(something)
		something.strftime("%H:%M")
	end

  def find_bookstores(places)
    @bookstores = []
    places.each do |p|
      if p.category == "Books"
        @bookstores << p
      end
    end
    return @bookstores
  end
end


#need to change to mon opening hours... mon closing hours etc

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "TransResourcesToronto" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&sensor=false" %>
    
    <%= csrf_meta_tags %>
  </head>

    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Home", resources_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
      <ul class="right">
      <% if current_user %>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Register", signup_path %></li>
      <% end %>
      </ul>
      <ul class="left">
        <li><%= link_to "Places", places_path %></li>
      </ul>
      <ul class="left">
        <li><%= link_to "Clothing Swap", users_path %></li>
      </ul>
      <ul class="left">
        <li><%= link_to "Forum", topics_path %></li>
      </ul>

      </section>
    </nav>

  <body>

    <%= yield %>
     <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/resources/edit.html.erb
<h1>Resources#edit</h1>
<p>Find me in app/views/resources/edit.html.erb</p>

app/views/resources/index.html.erb
<h1>Trans Resources Toronto</h1>


<h2>About Us</h2>
<p>Welcome to Trans Resources Toronto. If you live in Toronto, are transgender, and are looking for support, you've come to the right place.</p>

<p>Here we have a directory of locations in Toronto that will come in handy if you wish to physically and/or legally transition, want to read books with transgender topics, are looking for peer support, or otherwise get involved with your local community.</p>

<p>Click <%= link_to "Places", places_path %> in the navigation bar to see a list of all places sorted by category, or type a keyword into the search bar to help narrow down what you're looking for. Each place has a description of all they have to offer, an address, contact information, and a map to help you find all the resources in your vicinity. If you are homeless, there are also resources for meal plans and shelters that are trans-friendly.</p>

<p>If you are just beginning to transition, we know you may not have the funds or resources to replace your entire wardrobe, which is why we've created a <%= link_to "Clothing Swap", users_path %> for trans people. Here you can find listings with clothing trans people would like to trade, and what they're hoping to trade for. Once you <%= link_to "register", signup_path %> with us, you can post your own clothing and message people you would like to trade with. Everyone wins!</p>

<p>Finally, we have our own forum, <%= link_to "Superforum", topics_path %>, where you can directly speak with other users to discuss matters that are important to you, or share resources that we've missed. Feedback is very important to us and we would like to have the most comprehensive resource page for trans people in Toronto.</p>

<p>The reason we are called Trans Resources <i>Toronto</i> is because our resources are only in the Toronto area for now. We would like to expand someday to other places in Ontario where there are more resources and more trans people in need. Please post other places in Superforum that have come in handy for you!

<p>We hope you enjoy your stay here, and remember to <%= link_to "join us!", signup_path %></p>

app/views/resources/new.html.erb
<h1>Resources#new</h1>
<p>Find me in app/views/resources/new.html.erb</p>

app/views/resources/show.html.erb
<h1>Resources#show</h1>
<p>Find me in app/views/resources/show.html.erb</p>